### ISSUE TITLE
Sort changelog so that version bumps are grouped together?

### ISSUE THREAD

**Issue by dmcc** [home-assistant/hass-release#44]
This is extremely minor, but might make it easier to parse release notes. The idea would be that instead of the changes in github's order that we first show all non-version bumps, then all version bumps. For example, version 2022.12.2 could look like this:

[2022.12.2](https://github.com/home-assistant/core/releases/tag/2022.12.2)
Repository: [home-assistant/core](https://github.com/home-assistant/core) · Tag: [2022.12.2](https://github.com/home-assistant/core/tree/2022.12.2) · Commit: [9b4d863](https://github.com/home-assistant/core/commit/9b4d86399eec0a85ccb9de3ca30d654bbc19d6e4) · Released by: [balloob](https://github.com/balloob)

- Fix fibaro climate unit (@rappenze - #83659) (fibaro docs)
- Fix event sensor for UniFi Protect (@AngellusMortis - #83663) (unifiprotect docs)
- Add missing CONF_SPEED to sensor device_trigger SCHEMA (@SukramJ - #83679) (sensor docs)
- Fix delay setting up new Yale Access Bluetooth entries (@bdraco - #83683) (yalexs_ble docs)
- Fix loading of Fritz!Smarthome issues on older Fritz!Box (@mib1185 - #83688) (fritzbox docs)
- Fix IPv6 sensor is only loaded when Fritz!Box is in router mode (@mib1185 - #83757) (fritz docs)
- Fix scan_interval in Scrape (@gjohansson-ST - #83758) (scrape docs)

Version bumps:
- Bump pyrisco to 0.5.7 (@maartenweyns - #83548) (risco docs)
- Bump pychromecast to 13.0.2 (@emontnemery - #83625) (cast docs)
- Bump aioshelly to 5.1.1 (@thecode - #83680) (shelly docs)
- Bump androidtv dependency of androitv component (@chatziko - #83707) (androidtv docs)
- lifx: bump aiolifx_effects dependency to v0.3.1 (@Djelibeybi - #83730) (lifx docs)

If this is of interest, I'm happy to try to put together a PR.

**Comment by Djelibeybi** [comment]
It would be good if we can link the bumps to Home Assistant issues that the bump resolved. In the case of my bump for example, it resolved #83719 so an entry like this would be super peachy keen:

* Fix Lifx Effect Pulse Error (#83719) via lifx: bump aiolifx_effects dependency to v0.3.1 (@Djelibeybi - #83730)

Not sure if that's feasible or not though. :)

**Comment by frenck** [comment]
I think the suggested sorting doesn’t make much sense. Why would you group version bumps? 🤷‍♂️

Additionally, it breaks the timeline, as the order may matter.

**Comment by dmcc** [comment]
Maybe it's just me, in which case feel free to ignore this :) When I'm scanning the release notes I mostly want to know the new features/bug fixes. I generally only care about version bumps when they fix an upstream issue that I had been tracking.

**Comment by frenck** [comment]
Anything in a patch release fixes bugs (including the bumps), otherwise, it wouldn’t be in a patch release to begin with 🤷‍♂️

**Comment by dmcc** [comment]
> A patch release will never contain new features

Ah, thanks! Good to know. I'll close the issue and apologies for the spam.

**Comment by dmcc** [comment]
Here's a better thought out version of this FR: [Personalized changelog](https://community.home-assistant.io/t/personalized-changelog/407987)
